import { News } from "@/components/News/News";

export default function Home() {
  return (
      <News />
  )
}

export const metadata = {
  title: "News - Boxing",
  description: "Generated by create next app",
};